Add showBorder props
alma/widgets pull request #55
Opened 2022-06-07 12:21 UTC by benoitgrasset-alma

### Context

Add the possibility for the merchant to hide the border around the modal

new props: `showBorder` props

![Capture d’écran du 2022-06-07 14-20-35](https://user-images.githubusercontent.com/104012464/172377484-db2ca215-e331-469a-8e59-73a678abcabe.png)

2022-06-14 11:53 UTC, gautierlabarre requested changes
I don't see any test file, otherwise LGTM

2022-06-14 13:33 UTC, gautierlabarre approved these changes

2022-06-17 15:58 UTC, ncordin commented on documentation.md
> +- hideBorder: `boolean` [optional, default: true]
I saw a default value of `false` in the react component. I think the code is correct but the doc is wrong.

2022-06-17 16:00 UTC, ncordin commented on documentation.md
> +Hide the border if set to false, set to true as default
I think this line of the doc is also incorrect. 
It should be "hide when set to true" 👈 it's what the code does and what seams logic.

```suggestion
Hide the border if set to true, set to false as default
```👈

2022-06-17 16:01 UTC, ncordin approved these changes
Approved with 2 mistakes in the documents that are important to fix.

2022-06-20 08:14 UTC, benoitgrasset-alma commented on documentation.md
> +Hide the border if set to false, set to true as default
thanks, i changed my props from `showBorder` to `hideBorder` and forgot to update the doc

2022-06-20 08:20 UTC, merged